from battle_state import BattleState
from player_team import player_team
from llm_battle_controller import choose_ai_move

def run_battle(opponent_team_text, difficulty_level):
    battle = BattleState(player_team, opponent_team_text, difficulty_level)

    battle_history = []

    print("Battle started.")
    print("Opponent team generated by LLM:")
    print(opponent_team_text)

    active_player_pokemon = player_team[0]
    active_opponent_pokemon = "First opponent Pokémon from generated team"

    while battle.battle_over == False:
        battle.increase_turn()

        print()
        print("Turn " + str(battle.turn_count))
        print("Your active Pokémon: " + active_player_pokemon["name"])
        print("Choose a move:")

        for i in range(len(active_player_pokemon["moves"])):
            print(str(i + 1) + ". " + active_player_pokemon["moves"][i])

        choice = input("Move number: ")
        move_index = int(choice) - 1
        player_move = active_player_pokemon["moves"][move_index]

        ai_move = choose_ai_move(
            active_opponent_pokemon,
            active_player_pokemon,
            battle_history
        )

        print("Player used: " + player_move)
        print("Opponent used: " + ai_move)

        battle_history.append("Turn " + str(battle.turn_count) + ": Player used " + player_move + ", opponent used " + ai_move)

        if battle.turn_count >= 10:
            result = input("Did the player win? yes/no: ")

            if result == "yes":
                battle.end_battle(True)
            else:
                battle.end_battle(False)

    return battle